### ISSUE TITLE
Rate Limit error "Too Many Certificates issued for Daplie.me"

### ISSUE THREAD

**Issue by brysonchill** [Daplie/daplie.com#1]
failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: Too many certificates already issued for: daplie.me

**Comment by mathwhiz1212** [comment]
I'm pretty sure this is fixed by adding daplie.me to the public suffix list: https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat#L10788
